[package]
name = "lycan"
version = "0.1.0"
authors = ["Vaelden <maugan.villatel@gmail.com>"]

[lib]
name="lycan"
path="src/lib.rs"

[dependencies]
lazy_static = "*"
log = "*"
env_logger = "*"
rustc-serialize = "*"
time = "*"
mio = "*"
byteorder = "*"
threadpool = "*"
docopt = "*"
nalgebra = "*"
smallvec = "*"
rand = "*"
hyper = "0.6.16"
bytes = "*"

[dependencies.id]
git = "https://github.com/GreenPix/id-rs.git"

[dependencies.lycan-serialize]
git = "https://github.com/Greenpix/lycan-serialize.git"

[dependencies.aariba]
git = "https://github.com/GreenPix/aariba.git"

[[bin]]
name = "lycan"
doc = false

[features]
json = ["lycan-serialize/json"]

default = ["json"]
